/**
 * ALASKA TOUR & TRAVEL - GLOBAL & INDIA DESTINATIONS DATASET
 * 40 Curated World-Class Tourist Places (Famous & Hidden Gems)
 * Includes:
 * - 1-line short descriptions & famous spots (Gateway of India, Rani Baug, Taj Mahal, etc.)
 * - Categories: Historical, Hill Stations, Wildlife & Parks, Beaches, Cultural & Religious, Glaciers & Aurora
 * - Nearest Airport, Railway Station, Bus Stand for each destination
 * - Official ticket booking guidance & traveler tips
 */

const ALL_DESTINATIONS = [
  // =========================================================================
  // 1. HISTORICAL PLACES & MONUMENTS
  // =========================================================================
  {
    id: "mumbai",
    name: "Mumbai & Gateway of India",
    famousSpot: "Gateway of India, Marine Drive & Rani Baug (Byculla Zoo)",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Maharashtra",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "3 Days",
    durationDays: 3,
    price: 8500,
    rating: 4.8,
    reviewsCount: 4210,
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Chhatrapati Shivaji Maharaj Intl (BOM)",
    railway: "CSMT (VT) / Mumbai Central (BCT)",
    busStand: "Mumbai Central ST Stand / Borivali ISBT",
    shortDesc: "Bharat ki financial capital jahan colonial British architecture, Arabian Sea, Marine Drive sunsets aur historic Rani Baug zoo milte hain.",
    longDesc: "Mumbai is a vibrant metropolis blending rich colonial heritage, historic architecture, and the Arabian Sea coastline. Marvel at the 1911 Gateway of India arch, stroll along the Queen's Necklace at Marine Drive, visit Rani Baug (Veermata Jijabai Bhosale Botanical Udyan and Zoo), and take a heritage ferry to the ancient rock-cut Elephanta Caves.",
    highlights: [
      { title: "Gateway of India", sub: "Iconic basalt waterfront arch built in 1911 overlooking Mumbai harbour" },
      { title: "Rani Baug (Byculla Zoo)", sub: "Historic 53-acre botanical gardens housing Humboldt penguins and heritage trees" },
      { title: "Marine Drive Promenade", sub: "Scenic 3 km arc facing the Arabian Sea sunset and Queen's Necklace lights" },
      { title: "Elephanta Island Caves", sub: "UNESCO rock-cut 5th-century Shiva sculpture temple complex accessed via ferry" }
    ],
    tips: "Avoid peak local train rush hours (8:30-11 AM & 5-8 PM). Visit Marine Drive around 5:30 PM for a cool ocean breeze and sunset!"
  },
  {
    id: "agra",
    name: "Agra & The Taj Mahal",
    famousSpot: "Taj Mahal, Agra Fort & Mehtab Bagh",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Uttar Pradesh",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "2 Days",
    durationDays: 2,
    price: 6500,
    rating: 4.9,
    reviewsCount: 5400,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Agra Kheria Airport (AGR) / IGI New Delhi (DEL)",
    railway: "Agra Cantt (AGC) / Agra Fort (AF)",
    busStand: "ISBT Idgah Bus Stand, Agra",
    shortDesc: "Mughal architecture ka sabse bada aashcharya aur duniya ke 7 Ajoobon mein se ek shwet sangmarmar ka Taj Mahal.",
    longDesc: "Agra is world-renowned for the magnificent Taj Mahal, an ivory-white marble mausoleum commissioned in 1631 by Mughal Emperor Shah Jahan. Beyond the Taj Mahal, explore the massive red sandstone walls of Agra Fort, the abandoned Mughal royal city of Fatehpur Sikri, and view reflections of the Taj across the Yamuna River from Mehtab Bagh.",
    highlights: [
      { title: "The Taj Mahal", sub: "UNESCO World Heritage Wonder of the World in pure white Makrana marble" },
      { title: "Agra Fort", sub: "Massive 16th-century Mughal imperial walled palace fortress with Jahangir Mahal" },
      { title: "Fatehpur Sikri", sub: "Preserved red sandstone royal court and Buland Darwaza built by Emperor Akbar" },
      { title: "Mehtab Bagh", sub: "Moonlight riverside Mughal garden with stunning sunset reflections of the Taj" }
    ],
    tips: "Taj Mahal is closed on Fridays. Book sunrise tickets online via ASI portal to avoid crowds and witness golden morning light."
  },
  {
    id: "jaipur",
    name: "Jaipur & The Pink City Forts",
    famousSpot: "Hawa Mahal, Amer Fort & City Palace",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Rajasthan",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "3 Days",
    durationDays: 3,
    price: 9200,
    rating: 4.8,
    reviewsCount: 3800,
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Jaipur International Airport (JAI)",
    railway: "Jaipur Junction (JP) / Gandhinagar Jaipur (GADJ)",
    busStand: "Sindhi Camp Inter-State Bus Stand, Jaipur",
    shortDesc: "Rajputana shaan, vishal Amer Fort, 953 khidkiyon wala Hawa Mahal aur royal City Palace ka shahar.",
    longDesc: "Jaipur, the capital of Rajasthan, is known worldwide as the 'Pink City'. Its wide avenues are lined with terracotta-pink buildings, bustling bazaars selling handcrafted gems, and hilltop forts. Stand before the intricate honeycomb facade of Hawa Mahal, explore the mirror palaces of Amer Fort overlooking Maota Lake, and visit the historic Jantar Mantar observatory.",
    highlights: [
      { title: "Hawa Mahal (Palace of Winds)", sub: "Iconic 5-story pink facade with 953 honeycomb jharokhas" },
      { title: "Amer Fort & Sheesh Mahal", sub: "Hilltop fortress with dazzling hall of mirrored glass" },
      { title: "City Palace & Museum", sub: "Royal residence displaying Maharaja royal costumes and weapons" },
      { title: "Nahargarh Fort Sunset Point", sub: "Panoramic twilight views over the entire Jaipur cityscape" }
    ],
    tips: "Buy a combined 2-day composite monument pass at Amer Fort to save time and money across all major government monuments."
  },
  {
    id: "delhi",
    name: "Delhi & Mughal Heritage",
    famousSpot: "Red Fort, Qutub Minar, India Gate & Humayun's Tomb",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Delhi NCR",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "3 Days",
    durationDays: 3,
    price: 7900,
    rating: 4.8,
    reviewsCount: 4600,
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Indira Gandhi International Airport (DEL)",
    railway: "New Delhi (NDLS) / Old Delhi (DLI) / Hazrat Nizamuddin (NZM)",
    busStand: "ISBT Kashmere Gate / Anand Vihar ISBT",
    shortDesc: "Bharat ki historic rajdhani jahan Mughal saltanat ka Lal Qila, 73m uncha Qutub Minar aur Amar Jawan Jyoti India Gate hain.",
    longDesc: "Delhi is a living chronicle of eight historic empires. Walk through the monumental red sandstone bastions of the Mughal Red Fort, stand before the 73-meter tall 12th-century Qutub Minar, pay homage at the India Gate war memorial, and admire the Persian garden symmetry of Humayun's Tomb which inspired the Taj Mahal.",
    highlights: [
      { title: "The Red Fort (Lal Qila)", sub: "UNESCO 17th-century Mughal fortress where India's independence is celebrated" },
      { title: "Qutub Minar Complex", sub: "World's tallest brick minaret with the 1,600-year-old rust-resistant iron pillar" },
      { title: "India Gate & Kartavya Path", sub: "Grand 42-meter triumphal arch war memorial surrounded by green lawns" },
      { title: "Humayun's Tomb", sub: "Exquisite red sandstone Persian charbagh mausoleum built in 1570" }
    ],
    tips: "Use the Delhi Metro (Yellow and Violet lines) to beat city traffic and reach historical monuments quickly."
  },
  {
    id: "hampi",
    name: "Hampi & Vijayanagara Ruins",
    famousSpot: "Virupaksha Temple, Stone Chariot & Matanga Hill",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Karnataka",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "3 Days",
    durationDays: 3,
    price: 8900,
    rating: 4.9,
    reviewsCount: 2200,
    image: "https://images.unsplash.com/photo-1600100397608-f010f4453535?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to February",
    airport: "Jindal Vidyanagar (VDY) (35 km) / Hubballi (HBX)",
    railway: "Hosapete Junction (HPT) (13 km from Hampi)",
    busStand: "Hosapete KSRTC Bus Stand",
    shortDesc: "Surreal giant boulders ke beech 14th century Vijayanagara Samrajya ke vishal mandir aur prashidha Pathar ka Rath.",
    longDesc: "Set among surreal boulder-strewn hills along the Tungabhadra River, Hampi was once the capital of the mighty Vijayanagara Empire and the second-largest city in the world. Explore hundreds of monumental stone temples, the iconic Stone Chariot at Vijaya Vittala Temple, the royal Lotus Mahal, and climb Matanga Hill for an unforgettable sunrise over the ancient ruins.",
    highlights: [
      { title: "Stone Chariot & Vittala Temple", sub: "Masterpiece shrine with world-famous musical pillars" },
      { title: "Virupaksha Temple", sub: "Active 7th-century riverfront temple with a towering 160-ft gopuram" },
      { title: "Matanga Hill Sunrise", sub: "Panoramic 360-degree views across ancient ruins and river boulders" },
      { title: "Coracle Boat Ride", sub: "Traditional round wicker boat ride on the Tungabhadra River" }
    ],
    tips: "Rent a bicycle or electric moped to easily explore the expansive ruins across the Sacred and Royal centers."
  },
  {
    id: "khajuraho",
    name: "Khajuraho Temples & Sculptures",
    famousSpot: "Kandariya Mahadeva Temple & Western Group Complex",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Madhya Pradesh",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "2 Days",
    durationDays: 2,
    price: 7200,
    rating: 4.8,
    reviewsCount: 1840,
    image: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Khajuraho Airport (HJR)",
    railway: "Khajuraho Railway Station (KURJ)",
    busStand: "Khajuraho Central Bus Stand",
    shortDesc: "UNESCO world heritage site jahan 10th century Chandela dynasty ki adbhut stone carvings aur prachin shilpkala hai.",
    longDesc: "Constructed between 950 and 1050 AD by the Chandela dynasty, the temples of Khajuraho celebrate the multifaceted aspects of human life, divinity, and eroticism through breathtakingly detailed sandstone sculptures. The soaring spires of Kandariya Mahadeva Temple represent the zenith of medieval Indian temple architecture.",
    highlights: [
      { title: "Kandariya Mahadeva Temple", sub: "Soaring 31m spire adorned with over 800 intricately carved statues" },
      { title: "Lakshmana Temple", sub: "Preserved 10th-century shrine with exquisite stone battle and royal friezes" },
      { title: "Khajuraho Dance Festival", sub: "World-famous annual classical Indian dance festival held every February" },
      { title: "Raneh Waterfalls Canyon", sub: "Multi-colored granite canyon and canyon cascades 20 km away" }
    ],
    tips: "Attend the evening sound and light show narrated by Amitabh Bachchan in the western temple lawn."
  },
  {
    id: "paris",
    name: "Paris & The Eiffel Tower",
    famousSpot: "Eiffel Tower, Louvre Museum & Seine River",
    country: "europe",
    countryName: "🇪🇺 France",
    state: "Île-de-France",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "6 Days",
    durationDays: 6,
    price: 88000,
    rating: 4.8,
    reviewsCount: 3900,
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    bestSeason: "April to October",
    airport: "Paris Charles de Gaulle (CDG) / Orly (ORY)",
    railway: "Gare du Nord / Gare de Lyon (TGV)",
    busStand: "Paris Bercy Seine International Bus Terminal",
    shortDesc: "Pyar aur kala ki nagari! Iconic Eiffel Tower, Louvre museum mein Mona Lisa aur romantic Seine river cruise.",
    longDesc: "Paris, the City of Light, is celebrated for its world-class art, fashion, gastronomy, and historic boulevards. Climb the Eiffel Tower for timeless views of the city, see the Mona Lisa and Venus de Milo in the Louvre Museum, stroll the Champs-Élysées to the Arc de Triomphe, and glide down the Seine River on a sunset glass-roofed cruise.",
    highlights: [
      { title: "The Eiffel Tower", sub: "Wrought-iron landmark soaring over the Champ de Mars" },
      { title: "The Louvre Museum", sub: "The world's largest art museum housing over 35,000 treasures" },
      { title: "Seine River Cruise", sub: "Admire illuminated medieval bridges and Notre-Dame Cathedral" },
      { title: "Palace of Versailles", sub: "Gilded royal residence of King Louis XIV with Hall of Mirrors" }
    ],
    tips: "Pre-book timed-entry museum tickets online at least 3 weeks in advance to bypass multi-hour queues."
  },
  {
    id: "rome",
    name: "Rome & Ancient Colosseum",
    famousSpot: "The Colosseum, Trevi Fountain & Vatican City",
    country: "europe",
    countryName: "🇪🇺 Italy",
    state: "Lazio",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "5 Days",
    durationDays: 5,
    price: 82000,
    rating: 4.9,
    reviewsCount: 4100,
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80",
    bestSeason: "March to May / September to November",
    airport: "Rome Fiumicino Leonardo da Vinci (FCO)",
    railway: "Roma Termini Central Station",
    busStand: "Tiburtina Bus Station, Rome",
    shortDesc: "Ancient Roman Empire ka dil! Gladiator amphitheatre Colosseum, St. Peter's Basilica aur Trevi Fountain coin wish.",
    longDesc: "Rome is an open-air museum where nearly three millennia of history unfold at every street corner. Walk inside the awe-inspiring 2,000-year-old Colosseum where gladiators once clashed, toss a coin into the baroque waters of Trevi Fountain to ensure your return, explore the ancient Roman Forum, and visit the sovereign Vatican City with Michelangelo's Sistine Chapel ceiling.",
    highlights: [
      { title: "The Colosseum", sub: "World's largest standing amphitheatre capable of holding 80,000 spectators" },
      { title: "Vatican City & Sistine Chapel", sub: "Papal enclave featuring Michelangelo's legendary frescoes" },
      { title: "The Pantheon", sub: "Nearly 2,000-year-old roman temple with the world's largest unreinforced concrete dome" },
      { title: "Trevi Fountain", sub: "Iconic baroque fountain celebrated for coin-tossing tradition" }
    ],
    tips: "Book an early morning skip-the-line ticket for the Vatican Museums to view the Sistine Chapel before the crowds arrive."
  },
  {
    id: "cairo",
    name: "Cairo & The Great Pyramids",
    famousSpot: "Great Pyramids of Giza, Sphinx & Nile River",
    country: "egypt",
    countryName: "🇪🇬 Egypt",
    state: "Giza Governorate",
    category: "historical",
    categoryName: "🏰 Historical & Monuments",
    duration: "5 Days",
    durationDays: 5,
    price: 58000,
    rating: 4.9,
    reviewsCount: 3600,
    image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to April",
    airport: "Cairo International Airport (CAI)",
    railway: "Ramses Railway Station, Cairo",
    busStand: "Turgoman Cairo Bus Terminal",
    shortDesc: "Duniya ke sabse purane 4,500 saal prachin ajoobe: Khufu ka Pyramid, enigmatic Sphinx aur Nile river felucca sailing.",
    longDesc: "Cairo is the cradle of human civilization. Standing on the Giza plateau are the only remaining Wonder of the Ancient World: the Great Pyramid of Khufu, guarded by the mythical limestone Great Sphinx. Explore King Tutankhamun's golden treasures in the Grand Egyptian Museum and sail down the legendary Nile River on a traditional wooden felucca.",
    highlights: [
      { title: "The Great Pyramid of Giza", sub: "4,500-year-old monumental tomb of Pharaoh Khufu built from 2.3M limestone blocks" },
      { title: "The Great Sphinx of Giza", sub: "Mythical monumental statue with a lion's body and human pharaoh head" },
      { title: "Grand Egyptian Museum", sub: "World's largest archaeological museum housing King Tut's complete burial treasures" },
      { title: "Khan el-Khalili Bazaar", sub: "Vibrant medieval souk filled with spices, lanterns, and brassware" }
    ],
    tips: "Hire a licensed Egyptologist guide at Giza for fascinating historical context and to navigate camel ride vendors."
  },

  // =========================================================================
  // 2. HILL STATIONS & NATURE
  // =========================================================================
  {
    id: "srinagar",
    name: "Srinagar & Kashmir Valley",
    famousSpot: "Dal Lake Shikara, Mughal Gardens & Gulmarg Gondola",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Jammu & Kashmir",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "5 Days",
    durationDays: 5,
    price: 24500,
    rating: 4.9,
    reviewsCount: 3100,
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
    bestSeason: "April to Oct (Greenery) / Dec to Feb (Snow)",
    airport: "Sheikh ul-Alam Intl Airport Srinagar (SXR)",
    railway: "Udhampur (UHP) / Jammu Tawi (JAT)",
    busStand: "Tourist Reception Centre (TRC) Bus Stand, Srinagar",
    shortDesc: "Dharti ka jannat! Dal Lake par floating shikara rides, Asia ki highest Gulmarg gondola aur chinar ke ped.",
    longDesc: "Referred to as 'Paradise on Earth', Kashmir captivates visitors with the serene waters of Dal Lake, ornate hand-carved cedar houseboats, and terraced Persian Mughal Gardens like Shalimar Bagh. Nearby, Gulmarg offers the world's highest operational gondola cable car ascending to 13,780 feet for world-class skiing and alpine snow vistas.",
    highlights: [
      { title: "Dal Lake Shikara Ride", sub: "Glide past floating flower and vegetable markets at sunrise" },
      { title: "Gulmarg Gondola", sub: "Ascend Apharwat Peak on Asia's highest operational cable car" },
      { title: "Pahalgam Betaab Valley", sub: "Pristine pine forests along the turquoise Lidder River" },
      { title: "Shalimar & Nishat Gardens", sub: "Centuries-old Mughal terraced gardens overlooking the lake" }
    ],
    tips: "Pre-book Gulmarg Gondola Phase 2 tickets weeks in advance online, as tickets sell out rapidly during peak snow seasons."
  },
  {
    id: "manali",
    name: "Manali & Rohtang Pass",
    famousSpot: "Solang Valley, Atal Tunnel & Rohtang Snow Point",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Himachal Pradesh",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "4 Days",
    durationDays: 4,
    price: 13800,
    rating: 4.8,
    reviewsCount: 3900,
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80",
    bestSeason: "March to June (Summer) / Nov to Feb (Snow)",
    airport: "Kullu-Bhuntar Airport (KUU) (50 km) / Chandigarh (CDG)",
    railway: "Chandigarh Junction (CDG) / Kalka (KLK)",
    busStand: "Manali Private & HRTC Volvo Bus Terminal",
    shortDesc: "Snow adventure paradise! Solang valley mein paragliding, 13,058 ft Rohtang Pass aur world's longest Atal Tunnel.",
    longDesc: "Nestled in the Beas River valley of the Pir Panjal range, Manali is India's most popular mountain retreat. Adventure enthusiasts revel in paragliding, zorbing, and quad-biking in Solang Valley. Drive through the engineering marvel of the 9.02 km Atal Tunnel beneath the Rohtang Pass into the high-altitude Lahaul valley, and wander cobblestone lanes of Old Manali.",
    highlights: [
      { title: "Solang Valley Adventures", sub: "Paragliding, giant zorbing balls, and winter ski slopes" },
      { title: "Rohtang Pass (13,058 ft)", sub: "Gateway to Lahaul with panoramic glaciers and snowfields" },
      { title: "Atal Highway Tunnel", sub: "World's longest highway tunnel above 10,000 feet altitude" },
      { title: "Hadimba Devi Temple", sub: "1553 pagoda-style cedar wood forest temple in Dhungri Park" }
    ],
    tips: "Rohtang Pass permits are limited daily by the NGT and must be booked online 48 hours prior to your visit."
  },
  {
    id: "ooty",
    name: "Ooty & Nilgiri Blue Mountains",
    famousSpot: "Nilgiri Mountain Railway Toy Train, Ooty Lake & Doddabetta",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Tamil Nadu",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "3 Days",
    durationDays: 3,
    price: 9800,
    rating: 4.8,
    reviewsCount: 2900,
    image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to June",
    airport: "Coimbatore International Airport (CJB) (85 km)",
    railway: "Udhagamandalam (UAM) / Mettupalayam (MTP)",
    busStand: "Ooty Central Bus Stand (ATC)",
    shortDesc: "Queen of Hill Stations! UNESCO heritage steam toy train, shant Ooty lake aur 2,637-meter uncha Doddabetta Peak.",
    longDesc: "Perched high in the Western Ghats among eucalyptus-covered slopes and sprawling tea gardens, Ooty (Udhagamandalam) was the summer capital of the Madras Presidency. The century-old Nilgiri Mountain Railway toy train climbs through 16 tunnels and 250 bridges, while Doddabetta Peak offers sweeping views across the Blue Mountain ranges.",
    highlights: [
      { title: "Nilgiri Mountain Railway", sub: "UNESCO blue steam-engine train puffing through scenic mountain curves" },
      { title: "Ooty Lake & Boathouse", sub: "4-acre scenic artificial lake with motor and paddle boats" },
      { title: "Doddabetta Peak", sub: "Highest viewpoint in the Nilgiris (2,637m) with a telescope observatory" },
      { title: "Government Botanical Garden", sub: "Terraced 55-acre gardens housing a 20-million-year-old fossil tree trunk" }
    ],
    tips: "Book Nilgiri Toy Train tickets on IRCTC at least 30 days in advance as seats in the heritage coaches are strictly limited."
  },
  {
    id: "munnar",
    name: "Munnar Tea Hills & Anamudi",
    famousSpot: "Tata Tea Museum, Eravikulam & Mattupetty Dam",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Kerala",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "3 Days",
    durationDays: 3,
    price: 11200,
    rating: 4.9,
    reviewsCount: 3200,
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
    bestSeason: "September to May",
    airport: "Cochin International Airport (COK) (110 km)",
    railway: "Aluva (AWY) / Ernakulam Junction (ERS)",
    busStand: "Munnar KSRTC Central Bus Stand",
    shortDesc: "Hari-bhari chay ki bagan, daldali ghanti waterfalls aur Nilgiri Tahr ka ghar Eravikulam National Park.",
    longDesc: "Situated at the confluence of three mountain streams in the Idukki district, Munnar is draped in emerald manicured tea plantations and mist. Home to South India's highest mountain peak (Anamudi, 2,695m) and the endangered Nilgiri Tahr mountain goat in Eravikulam National Park, Munnar is also famous for the rare Neelakurinji flower blooming every 12 years.",
    highlights: [
      { title: "Eravikulam National Park", sub: "Sanctuary of the rare Nilgiri Tahr and rolling high-altitude grasslands" },
      { title: "Mattupetty Dam & Lake", sub: "Serene mountain reservoir offering thrilling speedboat rides" },
      { title: "Tata Tea Museum & Factory", sub: "Experience the complete journey of fresh green tea leaves to black tea" },
      { title: "Top Station Viewpoint", sub: "Panoramic cliffedge views looking down into neighboring Tamil Nadu valleys" }
    ],
    tips: "Early morning visits to the tea gardens offer wonderful photography with gentle morning sunlight cutting through misty valleys."
  },
  {
    id: "ziro",
    name: "Ziro Valley (Hidden Gem)",
    famousSpot: "Apatani Tribal Villages & Pine Groves",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Arunachal Pradesh",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "4 Days",
    durationDays: 4,
    price: 18500,
    rating: 4.8,
    reviewsCount: 890,
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80",
    bestSeason: "March to October (Ziro Festival in Sept)",
    airport: "Hollongi Donyi Polo Airport Itanagar (HGI)",
    railway: "Naharlagun Railway Station (NHLN)",
    busStand: "Ziro APST Bus Station",
    shortDesc: "Arunachal ki shant ghati, jahan Apatani tribe ki paramparik jeevanshaili aur Ziro Music Festival hota hai.",
    longDesc: "Tucked away in the eastern Himalayas of Arunachal Pradesh, Ziro Valley is a tranquil paradise of terraced emerald paddy fields and pine-clad hills. Home to the indigenous Apatani tribe—renowned for their sustainable wet-rice cultivation and unique cultural traditions—Ziro also hosts India's premier outdoor eco-music gathering, the Ziro Festival of Music.",
    highlights: [
      { title: "Apatani Heritage Villages", sub: "Meet elder tribespeople and learn ancient agricultural wisdom" },
      { title: "Kile Pakho Ridge Overlook", sub: "Stunning bird's-eye views of the plateau and snow peaks" },
      { title: "Tarin Fish Farm & Paddy Fields", sub: "Unique integrated fish-paddy sustainable agriculture" },
      { title: "Ziro Music Festival Grounds", sub: "Celebrated outdoor indie music festival among open valleys" }
    ],
    tips: "Indian nationals require an Inner Line Permit (ILP), which can easily be obtained online from the Arunachal government portal."
  },
  {
    id: "meghalaya",
    name: "Mawlynnong & Dawki (Hidden Gem)",
    famousSpot: "Umngot Glass River & Living Root Bridges",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Meghalaya",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "4 Days",
    durationDays: 4,
    price: 16500,
    rating: 4.9,
    reviewsCount: 1980,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to April (Glass river is clearest in Winter)",
    airport: "Shillong Airport Umroi (SHL) / Guwahati (GAU)",
    railway: "Guwahati Junction (GHY)",
    busStand: "ISBT Betkuchi, Guwahati / Shillong Stand",
    shortDesc: "Asia ka sabse saaf gaon aur transparent Umngot nadi jahan paani ke andar tak 20-feet patthar saaf dikhte hain.",
    longDesc: "Meghalaya, the 'Abode of Clouds', is famous for its wondrous bio-engineered living root bridges woven by Khasi tribes from the roots of rubber fig trees. Visit Mawlynnong, recognized as Asia's Cleanest Village, and travel to Dawki near the Bangladesh border to glide across the transparent turquoise waters of the Umngot River, so clear that boats appear to float in mid-air.",
    highlights: [
      { title: "Dawki Umngot River Boat Ride", sub: "Crystal-clear glass river with visible riverbeds 20 feet deep" },
      { title: "Nohkalikai Falls (Cherrapunji)", sub: "India's tallest plunge waterfall dropping 1,115 feet" },
      { title: "Single & Double Decker Root Bridges", sub: "Living architectural bridges grown across rain-fed gorges" },
      { title: "Mawlynnong Village", sub: "Spotless bamboo walkways, treehouses, and flower gardens" }
    ],
    tips: "Visit Dawki between November and March for the clearest transparent water. Avoid heavy monsoon months for boating."
  },
  {
    id: "swiss-alps",
    name: "Swiss Alps & Jungfraujoch",
    famousSpot: "Jungfraujoch 'Top of Europe' & Zermatt Matterhorn",
    country: "europe",
    countryName: "🇪🇺 Switzerland",
    state: "Bernese Oberland",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "7 Days",
    durationDays: 7,
    price: 115000,
    rating: 5.0,
    reviewsCount: 2800,
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80",
    bestSeason: "May to October (Summer) / Dec to March (Skiing)",
    airport: "Zurich Airport (ZRH) / Geneva (GVA)",
    railway: "Interlaken Ost / Grindelwald Terminal (SBB)",
    busStand: "Interlaken PostAuto Bus Terminal",
    shortDesc: "Top of Europe! Baraf se dhaki alpine chotiyan, turquoise mountain lakes, aur world-famous Glacier Express train.",
    longDesc: "Switzerland is the pinnacle of alpine beauty. Board the Eiger Express tricable gondola and the historic cogwheel train up to Jungfraujoch (3,454m), the highest railway station in Europe. Step out onto the Aletsch Glacier, visit the Ice Palace carved into the glacier, ride the Glacier Express panoramic train past Zermatt beneath the pyramid of the Matterhorn, and cruise the turquoise waters of Lake Brienz.",
    highlights: [
      { title: "Jungfraujoch (Top of Europe)", sub: "Highest railway station in Europe amidst massive glaciers" },
      { title: "The Matterhorn & Zermatt", sub: "Iconic pyramid-shaped peak surrounded by alpine villages" },
      { title: "Glacier Express Panoramic Train", sub: "The world's slowest express train crossing 291 bridges" },
      { title: "Interlaken & Lake Brienz", sub: "Adventure capital nestled between two emerald mountain lakes" }
    ],
    tips: "A Swiss Travel Pass provides unlimited travel on trains, boats, buses, and free entry to over 500 museums!"
  },
  {
    id: "kyoto",
    name: "Kyoto & Mount Fuji",
    famousSpot: "Fushimi Inari Torii Gates, Arashiyama & Lake Kawaguchi",
    country: "japan",
    countryName: "🇯🇵 Japan",
    state: "Kansai & Chubu",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "6 Days",
    durationDays: 6,
    price: 94000,
    rating: 4.9,
    reviewsCount: 3400,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    bestSeason: "March to May (Cherry Blossoms) / Oct to Nov (Autumn)",
    airport: "Kansai International (KIX) / Tokyo Haneda (HND)",
    railway: "Kyoto Station (Tokaido Shinkansen Bullet Train)",
    busStand: "Kyoto Station Karasuma Central Bus Terminal",
    shortDesc: "Japan ki paramparik sanskriti, 10,000 lal Torii gates, Arashiyama baans ka jangal aur barafila Mount Fuji volcano.",
    longDesc: "Kyoto is Japan's cultural heartland, home to over 2,000 Buddhist temples and Shinto shrines. Walk through thousands of vermilion torii gates at Fushimi Inari-taisha, wander through towering green stalks in the Arashiyama Bamboo Grove, and catch breathtaking reflections of symmetrical Mount Fuji (3,776m) across the calm waters of Lake Kawaguchi.",
    highlights: [
      { title: "Fushimi Inari-Taisha", sub: "Mountain trail lined with 10,000 bright vermilion wooden torii gates" },
      { title: "Mount Fuji & Lake Kawaguchi", sub: "Sacred snow-capped volcano peak mirrored in crystal lakes" },
      { title: "Arashiyama Bamboo Grove", sub: "Mesmerizing towering bamboo stalks that sway in the breeze" },
      { title: "Kinkaku-ji (Golden Pavilion)", sub: "Zen temple with top two floors covered in genuine gold leaf" }
    ],
    tips: "Get a 7-day JR Pass before arriving in Japan for unlimited high-speed Shinkansen bullet train rides between Tokyo, Kyoto, and Osaka."
  },
  {
    id: "banff",
    name: "Banff & Canadian Rockies",
    famousSpot: "Lake Louise, Moraine Lake & Banff Gondola",
    country: "canada",
    countryName: "🇨🇦 Canada",
    state: "Alberta",
    category: "hills",
    categoryName: "🏔️ Hill Stations & Nature",
    duration: "6 Days",
    durationDays: 6,
    price: 108000,
    rating: 4.9,
    reviewsCount: 2650,
    image: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=800&q=80",
    bestSeason: "June to September (Lakes) / Dec to March (Skiing)",
    airport: "Calgary International Airport (YYC) (140 km)",
    railway: "Rocky Mountaineer Luxury Train Terminal",
    busStand: "Banff High School Transit Center (Roam Transit)",
    shortDesc: "Turquoise neeli glacial jheelein Lake Louise aur Moraine Lake, Rocky mountains aur sulfur hot springs.",
    longDesc: "Banff National Park is Canada's oldest and most majestic national park. Its glacier-fed lakes, like Lake Louise and Moraine Lake in the Valley of the Ten Peaks, possess a vivid turquoise color caused by glacial rock flour. Take the Banff Gondola to the summit of Sulphur Mountain for 360-degree vistas across six mountain ranges.",
    highlights: [
      { title: "Lake Louise & Victoria Glacier", sub: "Iconic emerald-turquoise glacial lake with chateau boathouse" },
      { title: "Moraine Lake & Ten Peaks", sub: "Surreal blue alpine lake featured on the Canadian twenty-dollar bill" },
      { title: "Banff Sulphur Gondola", sub: "Ascend 2,281 meters for sweeping vistas of the Canadian Rockies" },
      { title: "Icefields Parkway", sub: "One of the most scenic mountain highways in the world" }
    ],
    tips: "Private cars are restricted at Moraine Lake; reserve Parks Canada shuttle tickets in advance online to secure access."
  },

  // =========================================================================
  // 3. BEACHES & COASTAL ESCAPES
  // =========================================================================
  {
    id: "goa",
    name: "Goa Coastal Beaches & Forts",
    famousSpot: "Baga Beach, Dudhsagar Falls & Fort Aguada",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Goa",
    category: "beaches",
    categoryName: "🏖️ Beaches & Coastal",
    duration: "4 Days",
    durationDays: 4,
    price: 14500,
    rating: 4.8,
    reviewsCount: 5100,
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to March",
    airport: "Dabolim (GOI) / Mopa Manohar Intl (GOX)",
    railway: "Madgaon (MAO) / Thivim (THVM)",
    busStand: "Kadamba Central Bus Terminal, Panaji / Mapusa",
    shortDesc: "Golden sand beaches, sea waves, Portuguese architecture, thrill water sports aur beachside seafood shacks.",
    longDesc: "Goa offers the quintessential tropical escape with over 100 kilometers of coastline facing the Arabian Sea. From the high-energy water sports, beach shacks, and night markets of North Goa (Baga, Anjuna, Calangute) to the serene palm-fringed sands and luxury resorts of South Goa (Palolem, Colva), visitors also enjoy 17th-century Portuguese cathedrals in Old Goa and four-tiered Dudhsagar Waterfalls.",
    highlights: [
      { title: "Dudhsagar Waterfalls", sub: "Four-tiered milky cascades deep inside Bhagwan Mahavir Sanctuary" },
      { title: "Fort Aguada & Lighthouse", sub: "1612 Portuguese coastal fort guarding the Mandovi River mouth" },
      { title: "Baga & Calangute Beaches", sub: "Jet skiing, parasailing, and lively beachfront shacks" },
      { title: "Basilica of Bom Jesus", sub: "UNESCO heritage church preserving the mortal remains of St. Francis Xavier" }
    ],
    tips: "Renting a scooter or self-drive car is the most convenient way to explore hidden coves, spice plantations, and historic forts."
  },
  {
    id: "andaman",
    name: "Andaman & Nicobar Islands",
    famousSpot: "Radhanagar Beach Havelock, Cellular Jail & Neil Island",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Andaman & Nicobar",
    category: "beaches",
    categoryName: "🏖️ Beaches & Coastal",
    duration: "5 Days",
    durationDays: 5,
    price: 28500,
    rating: 4.9,
    reviewsCount: 3100,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to May",
    airport: "Veer Savarkar International Airport, Port Blair (IXZ)",
    railway: "Connected via Direct Flights / Passenger Ships from Chennai & Kolkata",
    busStand: "Mohanpura Central Bus Stand, Port Blair",
    shortDesc: "Asia ka sabse sundar Radhanagar Beach, turquoise coral reefs, scuba diving aur azadi ki historic Cellular Jail.",
    longDesc: "The Andaman archipelago in the Bay of Bengal is celebrated for powdery white sand beaches, untouched coral reefs, and dense rainforests. Havelock Island (Swaraj Dweep) hosts Radhanagar Beach, voted Asia's best beach by Time Magazine. Dive into world-class scuba sites with manta rays, and pay homage to India's freedom fighters at the historic Cellular Jail in Port Blair.",
    highlights: [
      { title: "Radhanagar Beach (Beach No. 7)", sub: "Crescent of soft white sand and turquoise gentle waves" },
      { title: "Cellular Jail National Memorial", sub: "Historic colonial prison with inspiring evening light and sound show" },
      { title: "Elephant Beach Snorkeling", sub: "Shallow coral reefs teeming with colorful tropical reef fish" },
      { title: "Neil Island (Shaheed Dweep)", sub: "Relaxed tropical atmosphere with natural rock bridge formation" }
    ],
    tips: "Book high-speed private catamarans (Makruzz or Nautika) between Port Blair and Havelock well in advance."
  },
  {
    id: "alleppey",
    name: "Alleppey Backwaters & Houseboat",
    famousSpot: "Vembanad Lake Houseboat, Marari Beach & Kuttanad",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Kerala",
    category: "beaches",
    categoryName: "🏖️ Beaches & Coastal",
    duration: "3 Days",
    durationDays: 3,
    price: 13500,
    rating: 4.8,
    reviewsCount: 2850,
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    bestSeason: "September to March",
    airport: "Cochin International Airport (COK) (82 km)",
    railway: "Alappuzha Railway Station (ALLP)",
    busStand: "KSRTC Central Bus Station, Alleppey",
    shortDesc: "Venice of the East! Kerala ke shant backwaters mein traditional Kettuvallam luxury houseboat cruise aur coconut groves.",
    longDesc: "Alleppey (Alappuzha) is world-famous for its tranquil labyrinth of palm-fringed canals, lagoons, and paddy fields below sea level in Kuttanad. Board a converted traditional rice barge (Kettuvallam) equipped with furnished bedrooms and a private chef serving traditional Karimeen Pollichathu (pearl spot fish) while you glide peacefully through the backwaters.",
    highlights: [
      { title: "Overnight Luxury Houseboat Cruise", sub: "Private floating villa cruising scenic backwaters and villages" },
      { title: "Vembanad Lake Sunset", sub: "India's longest lake bustling with snake boat races during Onam" },
      { title: "Marari Quiet Beach", sub: "Untouched golden sand beach bordered by endless coconut palms" },
      { title: "Village Kayaking Tours", sub: "Navigate narrow scenic waterways that larger boats cannot enter" }
    ],
    tips: "Choose government-approved DTPC accredited houseboats for high hygiene, safety, and certified onboard chefs."
  },
  {
    id: "bali",
    name: "Bali & Uluwatu Cliffs",
    famousSpot: "Uluwatu Temple, Nusa Penida & Ubud Monkey Forest",
    country: "indonesia",
    countryName: "🇮🇩 Indonesia",
    state: "Bali Province",
    category: "beaches",
    categoryName: "🏖️ Beaches & Coastal",
    duration: "5 Days",
    durationDays: 5,
    price: 48000,
    rating: 4.9,
    reviewsCount: 4600,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    bestSeason: "April to October",
    airport: "Ngurah Rai International Airport Denpasar (DPS)",
    railway: "Island Trans-Sarbagita Network",
    busStand: "Ubung Bus Terminal, Denpasar",
    shortDesc: "Island of the Gods! Samundar ke kinare khadi pahadi par Uluwatu temple, Kecak fire dance aur Kelingking T-Rex beach.",
    longDesc: "Bali is an enchanting Indonesian island famed for volcanic mountains, iconic rice terraces, exotic coral reefs, and deeply rooted spiritual traditions. Watch the mesmerizing Kecak fire dance atop the 70-meter sea cliffs of Uluwatu Temple, hike down to the dramatic T-Rex shaped Kelingking Beach on Nusa Penida island, and visit the sacred monkey forest in Ubud.",
    highlights: [
      { title: "Uluwatu Cliff Temple & Fire Dance", sub: "Ancient clifftop temple with fiery sunset Kecak performances" },
      { title: "Nusa Penida & Kelingking Beach", sub: "Dramatic dinosaur-head cliff soaring over turquoise Indian Ocean" },
      { title: "Tegallalang Rice Terraces", sub: "Scenic cascading emerald paddies with famous giant jungle swings" },
      { title: "Seminyak & Canggu Beach Clubs", sub: "World-class beachfront dining, surfing, and twilight cocktails" }
    ],
    tips: "Indian passport holders can obtain an easy 30-day e-Visa on Arrival (e-VOA) online prior to departure."
  },
  {
    id: "phuket",
    name: "Phuket & Phi Phi Islands",
    famousSpot: "Maya Bay, James Bond Island & Big Buddha",
    country: "thailand",
    countryName: "🇹🇭 Thailand",
    state: "Phuket Province",
    category: "beaches",
    categoryName: "🏖️ Beaches & Coastal",
    duration: "5 Days",
    durationDays: 5,
    price: 39500,
    rating: 4.8,
    reviewsCount: 3900,
    image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to April",
    airport: "Phuket International Airport (HKT)",
    railway: "Phuket Smart Bus Route Network",
    busStand: "Phuket Bus Terminal 2",
    shortDesc: "Emerald Andaman Sagar ke limestone islands, movie famous Maya Bay beach aur vibrant night markets.",
    longDesc: "Thailand's largest island, Phuket, offers golden sandy shores backed by tropical hills. Take a thrilling speedboat excursion to the Phi Phi Islands to swim in the turquoise waters of Maya Bay, made world-famous by Hollywood cinema. Kayak through hidden sea lagoons and limestone caves in Phang Nga Bay beside James Bond Island, and visit the 45-meter tall white marble Big Buddha.",
    highlights: [
      { title: "Phi Phi Leh & Maya Bay", sub: "Sheltered emerald bay framed by 100-meter sheer limestone cliffs" },
      { title: "Phang Nga Bay (James Bond Island)", sub: "Dramatic sea karst pillars rising vertically out of emerald waters" },
      { title: "The Great Big Buddha", sub: "45-meter white Burmese marble statue offering 360-degree island views" },
      { title: "Phuket Old Town Bazaars", sub: "Charming Sino-Portuguese heritage shophouses and weekend walking street" }
    ],
    tips: "Book speedboats that depart early in the morning (around 7 AM) to enjoy Maya Bay before standard tourist boats arrive."
  },
  {
    id: "maldives",
    name: "Maldives Coral Atolls",
    famousSpot: "Overwater Villa Lagoon & Coral Reef Snorkeling",
    country: "maldives",
    countryName: "🇲🇻 Maldives",
    state: "Kaafu Atoll",
    category: "beaches",
    categoryName: "🏖️ Beaches & Coastal",
    duration: "4 Days",
    durationDays: 4,
    price: 68000,
    rating: 5.0,
    reviewsCount: 3100,
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to April",
    airport: "Velana International Airport, Malé (MLE)",
    railway: "Speedboat & Trans Maldivian Seaplane Transfers",
    busStand: "Malé City Ferry & Bus Terminal",
    shortDesc: "Crystal clear turquoise ocean mein floating villas, manta ray swimming aur luxury island relaxation.",
    longDesc: "Scattered across the Indian Ocean like a string of pearls, the Maldives consists of 26 natural ring-shaped coral atolls. Stay in luxury overwater bungalows perched directly above turquoise lagoons where reef sharks and stingrays glide beneath your glass floor. Indulge in world-class underwater restaurants, sunset dolphin cruises, and untouched snorkeling reefs.",
    highlights: [
      { title: "Overwater Lagoon Villas", sub: "Step directly from your private sun deck into crystal ocean waters" },
      { title: "Coral Reef Snorkeling with Turtles", sub: "Encounter sea turtles, reef sharks, and vibrant coral formations" },
      { title: "Seaplane Flightseeing", sub: "Thrilling aerial views over turquoise sandbars and ring atolls" },
      { title: "Sunset Dolphin Safari", sub: "Spot hundreds of spinner dolphins leaping alongside your boat" }
    ],
    tips: "Indian citizens receive a free 30-day visa on arrival. Opt for all-inclusive resort packages to save significantly on dining."
  },

  // =========================================================================
  // 4. WILDLIFE & NATIONAL PARKS
  // =========================================================================
  {
    id: "corbett",
    name: "Jim Corbett National Park",
    famousSpot: "Dhikala Zone Safari & Royal Bengal Tigers",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Uttarakhand",
    category: "wildlife",
    categoryName: "🐅 Wildlife & Safaris",
    duration: "3 Days",
    durationDays: 3,
    price: 12500,
    rating: 4.8,
    reviewsCount: 2600,
    image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to June",
    airport: "Pantnagar Airport (PGH) (80 km) / IGI New Delhi (DEL)",
    railway: "Ramnagar Railway Station (RMR) (Direct trains from Delhi)",
    busStand: "Ramnagar Central Bus Stand",
    shortDesc: "Bharat ka pehla national park jahan ghane sal forests mein Royal Bengal Tigers aur wild elephants dikhte hain.",
    longDesc: "Established in 1936 as Hailey National Park, Jim Corbett is India's oldest national park and the cradle of Project Tiger. Nestled along the Ramganga River in the Himalayan foothills, the park encompasses dense sal jungles and marshy grasslands. Embark on open 4x4 Gypsy safaris in the famous Dhikala and Bijrani zones to spot Royal Bengal tigers, wild Asian elephants, leopards, and over 600 bird species.",
    highlights: [
      { title: "Dhikala Forest Zone", sub: "Iconic grasslands overlooking the Ramganga reservoir" },
      { title: "Open 4x4 Jeep Safari", sub: "Track wild tigers, spotted deer, and barking deer" },
      { title: "Corbett Waterfall", sub: "Scenic 66-foot cascades surrounded by dense teak forest" },
      { title: "Garjiya Devi Temple", sub: "Hilltop river shrine perched on a giant rock in the Kosi River" }
    ],
    tips: "Dhikala zone night-stay permits must be booked on the official Corbett website up to 45 days in advance."
  },
  {
    id: "kaziranga",
    name: "Kaziranga National Park",
    famousSpot: "One-horned Rhinoceros, Elephant Safari & Brahmaputra",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Assam",
    category: "wildlife",
    categoryName: "🐅 Wildlife & Safaris",
    duration: "3 Days",
    durationDays: 3,
    price: 14200,
    rating: 4.9,
    reviewsCount: 2450,
    image: "https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to April",
    airport: "Jorhat Airport (JRH) (97 km) / Guwahati (GAU)",
    railway: "Furkating Junction (FKG) / Guwahati (GHY)",
    busStand: "Kohora Bus Stand, Kaziranga",
    shortDesc: "Duniya ke two-thirds one-horned rhinos ka ghar, vishal marshy grasslands aur UNESCO World Heritage site.",
    longDesc: "Kaziranga National Park on the floodplains of the Brahmaputra River in Assam is one of conservation's greatest success stories. Home to more than 2,400 Great Indian One-horned Rhinoceroses—over two-thirds of the world's population—the park also holds the highest density of Royal Bengal tigers in protected areas, wild water buffaloes, swamp deer, and Asian elephants.",
    highlights: [
      { title: "Great Indian One-horned Rhino", sub: "Get up close to prehistoric-looking armor-plated rhinos in open grasslands" },
      { title: "Dawn Elephant Safari", sub: "Glide quietly through morning mist on elephant back in the Kohora range" },
      { title: "Bagori & Agaratoli Jeep Safaris", sub: "Track tiger tracks, wild water buffalo herds, and exotic migratory birds" },
      { title: "Kakochang Waterfalls", sub: "Refreshing jungle cascades surrounded by rubber and tea estates nearby" }
    ],
    tips: "Book an early morning 5:30 AM elephant safari in the Central (Kohora) range for the best close-range rhino photography."
  },
  {
    id: "ranthambore",
    name: "Ranthambore National Park",
    famousSpot: "Machli Tiger Territory, Padam Talao & Ancient Fort",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Rajasthan",
    category: "wildlife",
    categoryName: "🐅 Wildlife & Safaris",
    duration: "3 Days",
    durationDays: 3,
    price: 13800,
    rating: 4.8,
    reviewsCount: 2900,
    image: "https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to June",
    airport: "Jaipur International Airport (JAI) (160 km)",
    railway: "Sawai Madhopur Junction (SWM) (11 km)",
    busStand: "Sawai Madhopur Central Bus Stand",
    shortDesc: "10th-century Ranthambore Fort ke niche khule jungle mein Royal Bengal Tigers ki open Gypsy safari.",
    longDesc: "Ranthambore is legendary as one of the best locations in the world to observe wild Royal Bengal tigers in their natural dry deciduous scrub habitat. The park is dominated by the imposing 10th-century UNESCO Ranthambore Fort that looms on a high plateau, surrounded by lakes where tigers often hunt spotted deer and sambar in broad daylight.",
    highlights: [
      { title: "Royal Bengal Tiger Sighting", sub: "Daytime tiger tracking across 10 designated wildlife safari zones" },
      { title: "Ranthambore UNESCO Fort", sub: "10th-century Chauhan fortress with ancient temples overlooking the reserve" },
      { title: "Padam & Rajbagh Lakes", sub: "Scenic watering holes frequented by marsh crocodiles and waterfowl" },
      { title: "Trinetra Ganesha Temple", sub: "Historic 3-eyed Ganesha shrine receiving letters of blessings from across India" }
    ],
    tips: "Zones 1 through 5 are historically considered the prime zones for tiger sightings; book Gypsy safaris 90 days in advance on the forest portal."
  },
  {
    id: "gir",
    name: "Gir National Park",
    famousSpot: "Asiatic Lions Safari & Devalia Interpretation Zone",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Gujarat",
    category: "wildlife",
    categoryName: "🐅 Wildlife & Safaris",
    duration: "3 Days",
    durationDays: 3,
    price: 11900,
    rating: 4.8,
    reviewsCount: 2200,
    image: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80",
    bestSeason: "December to March",
    airport: "Keshod Airport (IXK) (60 km) / Rajkot (RAJ) (160 km)",
    railway: "Junagadh Junction (JND) (60 km) / Veraval (VRL)",
    busStand: "Sasan Gir GSRTC Bus Stand",
    shortDesc: "Africa ke bahar duniya mein Asiatic Lions ka akela natural aawaas aur dry deciduous teak forests.",
    longDesc: "Gir Forest National Park and Wildlife Sanctuary is the sole remaining natural abode on Earth of the majestic Asiatic Lion (Panthera leo persica). Spanning rugged rocky hills and dry teak jungles in southwestern Gujarat, the sanctuary is also home to over 300 leopards, chital, nilgai, and the Maldhari pastoralist tribe who have coexisted with lions for centuries.",
    highlights: [
      { title: "Asiatic Lion Safaris", sub: "Encounter prides of rare Asiatic lions roaming freely in natural habitat" },
      { title: "Devalia Safari Park", sub: "Fenced eco-tourism zone guaranteeing quick wildlife observation" },
      { title: "Kamleshwar Dam Reservoir", sub: "Scenic reservoir called the lifeline of Gir, harboring marsh crocodiles" },
      { title: "Somnath Temple Excursion", sub: "Sacred Jyotirlinga seaside temple located just 45 km from Sasan Gir" }
    ],
    tips: "Gir permits must be booked on the official Gujarat forest department website. The park remains closed during monsoons (June 16 to Oct 15)."
  },
  {
    id: "serengeti",
    name: "Serengeti National Park",
    famousSpot: "The Great Wildebeest Migration & African Big Five",
    country: "tanzania",
    countryName: "🇹🇿 Tanzania, Africa",
    state: "Mara Region",
    category: "wildlife",
    categoryName: "🐅 Wildlife & Safaris",
    duration: "6 Days",
    durationDays: 6,
    price: 145000,
    rating: 5.0,
    reviewsCount: 2900,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    bestSeason: "June to October (Migration & Mara River crossing)",
    airport: "Kilimanjaro International (JRO) / Seronera Airstrip (SEU)",
    railway: "Arusha Regional Safari Transit Hub",
    busStand: "Arusha Central Safari Station",
    shortDesc: "Duniya ka sabse vishal wild animal migration! 2 million wildebeest, zebras aur lions, leopards, elephants ka jangal.",
    longDesc: "The Serengeti in Tanzania is nature's grandest stage. Spanning 14,750 square kilometers of endless golden savannah plains, it hosts the Great Migration—where over 1.5 million blue wildebeests and 250,000 zebras brave crocodile-infested Mara River crossings in a relentless circular trek. It also boasts the highest density of large predators on the African continent.",
    highlights: [
      { title: "The Great Wildebeest Migration", sub: "Witness thundering herds crossing the perilous crocodile-filled Mara River" },
      { title: "African 'Big Five' Safaris", sub: "Encounter lions, leopards, African bush elephants, black rhinos, and cape buffalo" },
      { title: "Sunrise Hot Air Balloon Safari", sub: "Float silently over endless golden plains as predators hunt at dawn" },
      { title: "Ngorongoro Crater Floor", sub: "Vast volcanic caldera holding an extraordinary density of wild animals" }
    ],
    tips: "Combine the northern Serengeti with the Ngorongoro Conservation Area for an unforgettable safari expedition."
  },

  // =========================================================================
  // 5. CULTURAL & RELIGIOUS SITES
  // =========================================================================
  {
    id: "varanasi",
    name: "Varanasi (Kashi)",
    famousSpot: "Dashashwamedh Ghat, Kashi Vishwanath & Assi Ghat",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Uttar Pradesh",
    category: "religious",
    categoryName: "🛕 Cultural & Religious",
    duration: "3 Days",
    durationDays: 3,
    price: 7800,
    rating: 4.9,
    reviewsCount: 4500,
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Lal Bahadur Shastri Airport, Babatpur (VNS)",
    railway: "Varanasi Junction (BSB) / DDU Junction",
    busStand: "Varanasi Cantt Bus Stand",
    shortDesc: "Duniya ki sabse purani jeevant nagari, jahan sham ki maha Ganga Aarti aur spiritual ghats ka anubhav milta hai.",
    longDesc: "Varanasi, situated on the sacred banks of the holy River Ganges, is considered the spiritual heartbeat of India. Witness the hypnotic evening Maha Aarti ceremony at Dashashwamedh Ghat with brass oil lamps and conch shells. Take a dawn boat ride along the 88 ancient stone ghats and seek blessings at the sacred golden spires of Kashi Vishwanath Temple.",
    highlights: [
      { title: "Dashashwamedh Maha Aarti", sub: "Synchronized spiritual fire ritual performed by Hindu priests" },
      { title: "Sunrise Ganga Boat Ride", sub: "Observe morning prayers and spiritual bathing rituals on the river" },
      { title: "Kashi Vishwanath Corridor", sub: "Grand historic temple complex dedicated to Lord Shiva" },
      { title: "Sarnath Deer Park", sub: "Where Lord Buddha gave his first sermon after enlightenment" }
    ],
    tips: "Hire a licensed rowboat at Assi Ghat at 5:30 AM to watch the sun rise over the Ganges while floating down to Manikarnika Ghat."
  },
  {
    id: "amritsar",
    name: "Amritsar & Golden Temple",
    famousSpot: "Sri Harmandir Sahib, Wagah Border & Jallianwala Bagh",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Punjab",
    category: "religious",
    categoryName: "🛕 Cultural & Religious",
    duration: "2 Days",
    durationDays: 2,
    price: 6800,
    rating: 5.0,
    reviewsCount: 5200,
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Sri Guru Ram Dass Jee Intl Airport (ATQ)",
    railway: "Amritsar Junction (ASR)",
    busStand: "Amritsar Inter-State Bus Terminal (ISBT)",
    shortDesc: "Pavitra sone se bana Harmandir Sahib, 24-ghante chalne wala vishal Langar aur Indo-Pak Wagah Border parade.",
    longDesc: "Amritsar is the spiritual and cultural capital of the Sikh faith. Stand in awe before Sri Harmandir Sahib (The Golden Temple), gilded in pure gold and surrounded by the holy Amrit Sarovar pool. Experience the world's largest community kitchen (Guru ka Langar) serving over 100,000 free hot meals daily to all people, visit the tragic historic grounds of Jallianwala Bagh, and witness the patriotic Beating Retreat Ceremony at the Indo-Pak Wagah Border.",
    highlights: [
      { title: "Sri Harmandir Sahib (Golden Temple)", sub: "Gilded holy shrine reflecting brilliantly across the sacred holy pool" },
      { title: "World's Largest Free Langar", sub: "Volunteer-run community kitchen feeding 100,000 pilgrims daily with love" },
      { title: "Wagah Border Beating Retreat", sub: "Electrifying military drill and flag-lowering ceremony at the border" },
      { title: "Jallianwala Bagh Memorial", sub: "Preserved historic park with bullet marks commemorating 1919 martyrs" }
    ],
    tips: "Cover your head with a scarf and remove footwear before entering the Golden Temple complex. Visit once at midnight to witness the Sukhasan ceremony."
  },
  {
    id: "tirupati",
    name: "Tirupati Balaji & Tirumala",
    famousSpot: "Lord Venkateswara Temple & Tirumala Seven Hills",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Andhra Pradesh",
    category: "religious",
    categoryName: "🛕 Cultural & Religious",
    duration: "2 Days",
    durationDays: 2,
    price: 5900,
    rating: 4.9,
    reviewsCount: 4800,
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    bestSeason: "September to March",
    airport: "Tirupati Airport Renigunta (TIR)",
    railway: "Tirupati Main (TPTY) / Renigunta (RU)",
    busStand: "Tirupati Central RTC Bus Stand",
    shortDesc: "Duniya ke sabse pavitra mandiron mein se ek, Tirumala ke 7 pahadon par sthit Bhagwan Balaji ka divya darshan.",
    longDesc: "Resting atop the seven holy peaks of the Seshachalam Hills in Tirumala, the Venkateswara Temple is the most visited and wealthiest religious pilgrimage shrine in the world. Pilgrims from all corners of the globe climb the sacred pedestrian pathway (Srivari Mettu or Alipiri) to seek the divine blessings of Lord Balaji (an incarnation of Lord Vishnu) and receive the sacred Tirupati Laddu Prasadam.",
    highlights: [
      { title: "Lord Venkateswara Temple", sub: "Dravidian architectural gem with pure gold Ananda Nilayam vimana tower" },
      { title: "Srivari Mettu Pilgrimage Trek", sub: "Sacred stone stairway climbing through lush Eastern Ghat hills" },
      { title: "Silathoranam Natural Arch", sub: "Rare geological rock arch dating back 2.5 billion years" },
      { title: "Sri Padmavathi Ammavari Temple", sub: "Sacred riverside shrine dedicated to Goddess Padmavathi in Tiruchanur" }
    ],
    tips: "Book Special Entry Darshan (SED ₹300 tickets) online on the official TTD (tirupatibalaji.ap.gov.in) portal 2-3 months in advance."
  },
  {
    id: "madurai",
    name: "Madurai & Meenakshi Temple",
    famousSpot: "Meenakshi Amman Temple 14 Gopurams & Thirumalai Palace",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Tamil Nadu",
    category: "religious",
    categoryName: "🛕 Cultural & Religious",
    duration: "2 Days",
    durationDays: 2,
    price: 6400,
    rating: 4.9,
    reviewsCount: 3700,
    image: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Madurai Airport (IXM)",
    railway: "Madurai Junction (MDU)",
    busStand: "Mattuthavani Integrated Bus Terminal, Madurai",
    shortDesc: "Dravidian architecture ka chamatkar, 14 vishal rang-birange moortiyon se saje gopurams aur hazaar khambhon wala hall.",
    longDesc: "Madurai is one of the oldest continuously inhabited cities in the world, built in concentric squares around the historic Meenakshi Sundareswarar Temple on the banks of the Vaigai River. The temple complex is renowned for its 14 monumental gateway towers (gopurams) soaring up to 52 meters, adorned with thousands of painted mythological figures and the Hall of a Thousand Pillars.",
    highlights: [
      { title: "Meenakshi Amman Temple", sub: "Marvel of Dravidian engineering with 14 vibrant sculpted gopurams" },
      { title: "Hall of a Thousand Pillars", sub: "985 intricately sculpted stone pillars with musical rock pillars" },
      { title: "Thirumalai Nayakkar Mahal", sub: "17th-century Indo-Saracenic royal palace with massive white pillars" },
      { title: "Gandhi Memorial Museum", sub: "Preserved historic residence holding Mahatma Gandhi's blood-stained dhoti" }
    ],
    tips: "Attend the evening 9:00 PM temple procession where Lord Sundareswarar is carried to Goddess Meenakshi's silver sanctum."
  },
  {
    id: "bodhgaya",
    name: "Bodh Gaya & Bodhi Tree",
    famousSpot: "Mahabodhi Temple UNESCO & Sacred Bodhi Tree",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Bihar",
    category: "religious",
    categoryName: "🛕 Cultural & Religious",
    duration: "2 Days",
    durationDays: 2,
    price: 5500,
    rating: 4.8,
    reviewsCount: 2900,
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    bestSeason: "October to March",
    airport: "Gaya International Airport (GAY) (12 km)",
    railway: "Gaya Junction (GAYA) (16 km)",
    busStand: "Bodh Gaya BSRTC Bus Stand",
    shortDesc: "Buddhism ka param sthan jahan Bhagwan Buddha ko Bodhi ped ke niche gyan (enlightenment) prapt hua tha.",
    longDesc: "Bodh Gaya is the holiest pilgrimage site in Buddhism. In approximately 500 BCE, Prince Siddhartha Gautama attained supreme enlightenment under the sacred Bodhi Tree (Ficus religiosa) here and became the Buddha. The 50-meter-tall pyramidal Mahabodhi Temple, originally founded by Emperor Ashoka in the 3rd century BCE, stands right beside the descendants of the original Bodhi Tree and Vajrasana (Diamond Throne).",
    highlights: [
      { title: "The Sacred Bodhi Tree", sub: "Descendant of the original pipal tree under which the Buddha meditated" },
      { title: "Mahabodhi Temple Complex", sub: "UNESCO 50m sandstone pyramidal spire adorned with classical Buddhist motifs" },
      { title: "The Great 80-Foot Buddha", sub: "Colossal stone statue of Lord Buddha seated in meditation pose" },
      { title: "International Monasteries", sub: "Monasteries built in traditional Thai, Tibetan, Bhutanese, and Japanese styles" }
    ],
    tips: "Spend quiet time meditating in the peaceful gardens behind the main Mahabodhi spire during early morning or twilight hours."
  },
  {
    id: "angkorwat",
    name: "Siem Reap & Angkor Wat",
    famousSpot: "Angkor Wat Sunrise, Bayon Smiling Faces & Ta Prohm",
    country: "cambodia",
    countryName: "🇰🇭 Cambodia",
    state: "Siem Reap Province",
    category: "religious",
    categoryName: "🛕 Cultural & Religious",
    duration: "4 Days",
    durationDays: 4,
    price: 44000,
    rating: 5.0,
    reviewsCount: 3800,
    image: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to March",
    airport: "Siem Reap-Angkor International Airport (SAI)",
    railway: "Royal Railway Cambodia / Tuk-Tuk Network",
    busStand: "Chong Kov Sou Siem Reap Central Bus Terminal",
    shortDesc: "Duniya ka sabse bada dhrmik mandir complex, 12th century Khmer empire ka adbhut stone marvel.",
    longDesc: "Angkor Wat in Siem Reap is the largest religious monument in the world, spanning over 400 acres. Originally dedicated to the Hindu God Vishnu before gradually transforming into a Buddhist temple, its five lotus-shaped towers represent the peaks of sacred Mount Meru. Explore the 216 giant smiling stone faces of Bayon temple and Ta Prohm, where massive jungle silk-cotton tree roots envelop ancient stone corridors.",
    highlights: [
      { title: "Angkor Wat Sunrise Reflection", sub: "Iconic sunrise over the sacred water lily reflection pond" },
      { title: "Bayon Temple Faces", sub: "Mysterious smiling stone faces of King Jayavarman VII looking in all directions" },
      { title: "Ta Prohm 'Tomb Raider' Temple", sub: "Atmospheric ruins entwined with colossal strangler fig tree roots" },
      { title: "Banteay Srei", sub: "Exquisite pink sandstone temple featuring the most delicate carvings in Khmer art" }
    ],
    tips: "Purchase the 3-day Angkor temple pass to explore at a relaxed pace without temple fatigue."
  },

  // =========================================================================
  // 6. GLACIERS, ARCTIC & DESERT ADVENTURES
  // =========================================================================
  {
    id: "denali",
    name: "Denali National Park, Alaska",
    famousSpot: "Mount McKinley (20,310 ft) & Tundra Wildlife Safari",
    country: "alaska",
    countryName: "🇺🇸 Alaska, USA",
    state: "Interior Alaska",
    category: "glaciers",
    categoryName: "❄️ Glaciers & Aurora",
    duration: "6 Days",
    durationDays: 6,
    price: 78500,
    rating: 4.9,
    reviewsCount: 2340,
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80",
    bestSeason: "Late May to Mid September",
    airport: "Ted Stevens Anchorage (ANC) / Fairbanks (FAI)",
    railway: "Denali Depot (Alaska Railroad Denali Star)",
    busStand: "Denali Park Visitors Center Transit",
    shortDesc: "North America ki sabse unchi choti (20,310 ft Mount McKinley) aur 6 million acres ka untouched tundra safari.",
    longDesc: "Denali National Park is the ultimate frontier wilderness experience. Towering beneath North America's highest peak (Mount McKinley, 20,310 ft), you will encounter grizzly bears, moose, wolves, and caribou roaming freely across glacial braided rivers and alpine tundra. Board the glass-domed Alaska Railroad and embark on breathtaking glacier flightseeing tours.",
    highlights: [
      { title: "Mount McKinley (20,310 ft)", sub: "Highest mountain peak in North America surrounded by massive glaciers" },
      { title: "Tundra Wilderness Safari", sub: "Spot wild grizzly bears, moose, dall sheep, and wolves in the wild" },
      { title: "Savage River Alpine Hike", sub: "Pristine glacial river valleys, tundra mosses, and alpine trails" },
      { title: "Alaska Railroad Glass Dome Train", sub: "Panoramic luxury rail voyage through mountain passes and canyons" }
    ],
    tips: "Summer temperatures range from 10°C to 20°C. Bring high-zoom binoculars, insect repellent, and layered weatherproof jackets."
  },
  {
    id: "fairbanks",
    name: "Fairbanks Aurora & Hot Springs",
    famousSpot: "Aurora Borealis & Chena Geothermal Pool",
    country: "alaska",
    countryName: "🇺🇸 Alaska, USA",
    state: "Interior Alaska",
    category: "glaciers",
    categoryName: "❄️ Glaciers & Aurora",
    duration: "4 Days",
    durationDays: 4,
    price: 74500,
    rating: 4.8,
    reviewsCount: 3120,
    image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=800&q=80",
    bestSeason: "September to Mid-April",
    airport: "Fairbanks International Airport (FAI)",
    railway: "Fairbanks Alaska Railroad Depot",
    busStand: "Fairbanks Transit Center",
    shortDesc: "Duniya ka sabse famous Northern Lights spot! Baraf ke beech natural 41°C hot springs aur husky sledding.",
    longDesc: "Situated directly under the auroral oval, Fairbanks provides the highest statistical probability of witnessing the dancing green, violet, and crimson curtains of the Northern Lights (Aurora Borealis). Soak in natural outdoor geothermal mineral pools at Chena Hot Springs while snow falls all around you, and mush your own team of Alaskan huskies through snow-draped pine forests.",
    highlights: [
      { title: "Aurora Borealis Viewing", sub: "World-class vibrant Northern Lights dancing in clear arctic night skies" },
      { title: "Chena Hot Springs", sub: "Natural outdoor 41°C geothermal mineral springs surrounded by winter snow" },
      { title: "Aurora Ice Museum", sub: "World's largest year-round ice sculpture castle and sub-zero ice cocktail bar" },
      { title: "Alaskan Husky Dog Sledding", sub: "Drive your own dog team through snowy boreal birch forests" }
    ],
    tips: "Visit during the new moon phase for the darkest night skies and highest contrast aurora photography!"
  },
  {
    id: "kenai",
    name: "Kenai Fjords & Seward, Alaska",
    famousSpot: "Exit Glacier, Resurrection Bay & Orca Whales",
    country: "alaska",
    countryName: "🇺🇸 Alaska, USA",
    state: "Southcentral Alaska",
    category: "glaciers",
    categoryName: "❄️ Glaciers & Aurora",
    duration: "4 Days",
    durationDays: 4,
    price: 71500,
    rating: 4.9,
    reviewsCount: 2180,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    bestSeason: "May to September",
    airport: "Ted Stevens Anchorage Intl (ANC) (200 km)",
    railway: "Seward Alaska Railroad Coastal Classic Depot",
    busStand: "Seward Small Boat Harbor Transit",
    shortDesc: "Vishal neele tidewater glaciers jo samundar mein girte hain, jumping humpback whales aur playful sea otters.",
    longDesc: "Where the massive Harding Icefield spills down into dramatic ocean fjords, Kenai Fjords National Park offers an unforgettable marine safari. Take an exhilarating boat cruise through Resurrection Bay to witness massive tidewater glaciers calving house-sized icebergs into the sea with a thunderous roar, and watch for breeching humpback whales, orcas, puffins, and playful sea otters.",
    highlights: [
      { title: "Tidewater Glacier Calving", sub: "Listen to the 'white thunder' as gigantic blocks of glacial ice crash into the sea" },
      { title: "Resurrection Bay Whale Cruise", sub: "Watch orca pods, humpback whales, and harbor seals in their marine habitat" },
      { title: "Exit Glacier Hike", sub: "Walk directly up to the face of an active retreating glacier along paved trails" },
      { title: "Alaska SeaLife Center", sub: "Renowned marine mammal rescue center with puffins, sea lions, and octopuses" }
    ],
    tips: "Take the Alaska Railroad Coastal Classic train from Anchorage to Seward for one of the most scenic coastal rail journeys on Earth."
  },
  {
    id: "spiti",
    name: "Spiti Valley (Hidden Gem)",
    famousSpot: "Key Monastery & Chandratal Moon Lake",
    country: "india",
    countryName: "🇮🇳 India",
    state: "Himachal Pradesh",
    category: "glaciers",
    categoryName: "❄️ Glaciers & Aurora",
    duration: "6 Days",
    durationDays: 6,
    price: 26000,
    rating: 4.9,
    reviewsCount: 1450,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    bestSeason: "May to October",
    airport: "Kullu-Bhuntar Airport (KUU) / Chandigarh (CDG)",
    railway: "Shimla (Toy Train) / Chandigarh Junction (CDG)",
    busStand: "Kaza Central HRTC Bus Terminal",
    shortDesc: "The 'Middle Land' between India and Tibet. High-altitude cold desert, ancient cliffside monasteries aur crystal blue Chandratal Lake.",
    longDesc: "Spiti Valley is an awe-inspiring cold desert nestled high in the Himalayas at over 12,500 feet. Dotted with whitewashed Buddhist gompas perched dramatically on cliff edges, Spiti offers raw, untouched grandeur. Visit the 1,000-year-old Key Monastery, send a postcard from Hikkim (the world's highest post office), and camp beside the crescent-shaped blue waters of Chandratal Lake.",
    highlights: [
      { title: "Key Gompa (Monastery)", sub: "1,000-year-old fortress monastery overlooking the Spiti River" },
      { title: "Chandratal Lake (Moon Lake)", sub: "Crescent-shaped high alpine lake at 14,000 feet" },
      { title: "Hikkim & Komic Villages", sub: "World's highest post office and highest motorable village" },
      { title: "Chicham Bridge", sub: "Asia's highest suspension bridge spanning a deep gorge" }
    ],
    tips: "Take 2 full days for gradual acclimatization to avoid altitude sickness (AMS). Keep cash handy as ATMs in Kaza are limited."
  },
  {
    id: "dubai",
    name: "Dubai Skyline & Red Desert Safari",
    famousSpot: "Burj Khalifa, Palm Jumeirah & Desert Camp",
    country: "uae",
    countryName: "🇦🇪 UAE",
    state: "Dubai",
    category: "glaciers",
    categoryName: "🏙️ Modern Marvels & Desert",
    duration: "5 Days",
    durationDays: 5,
    price: 52000,
    rating: 4.9,
    reviewsCount: 4800,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    bestSeason: "November to March",
    airport: "Dubai International Airport (DXB)",
    railway: "Dubai Metro Red Line (Burj Khalifa / Dubai Mall Station)",
    busStand: "Al Ghubaiba Inter-Emirate Bus Station",
    shortDesc: "Duniya ki sabse unchi imarat Burj Khalifa, futuristic Palm Jumeirah aur thrilling red dune desert safari.",
    longDesc: "Dubai is an ultra-modern global wonderland rising out of the Arabian Desert. Stand atop the 148th floor observation deck of Burj Khalifa (828 meters tall), marvel at the fountain shows at Dubai Mall, cruise on a luxury yacht past the Atlantis on Palm Jumeirah, and enjoy sunset dune bashing in the red sand desert followed by a traditional bedouin barbecue.",
    highlights: [
      { title: "Burj Khalifa At The Top", sub: "World's tallest building with panoramic views across the Arabian Gulf" },
      { title: "Desert 4x4 Dune Bashing", sub: "Thrilling roller-coaster ride over towering desert sand dunes" },
      { title: "Dubai Frame & Museum of Future", sub: "Stunning architectural feats showcasing human innovation" },
      { title: "Gold & Spice Souks", sub: "Traditional Arabian trading bazaars along Dubai Creek" }
    ],
    tips: "Metro cards (Nol Card) are very economical and connect the airport, downtown, marina, and major malls."
  }
];
